#!/usr/bin/env python3
"""
BBRI / any stock — Technical Analysis Chart Generator
Generated by OWL for stock-technical-analysis skill.

Usage:
  python3 generate_charts.py TICKER [PERIOD]
  python3 generate_charts.py BBRI.JK 6mo
  python3 generate_charts.py AAPL 1y

Requirements: yfinance, mplfinance, pandas, matplotlib
Install: pip install yfinance mplfinance pandas matplotlib
"""

import sys
import yfinance as yf
import mplfinance as mpf
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

def generate(ticker_str: str = "BBRI.JK", period: str = "6mo"):
    print(f"Downloading {ticker_str} ({period})...")
    ticker = yf.Ticker(ticker_str)
    df = ticker.history(period=period)
    
    if df.empty:
        print("ERROR: No data returned")
        return

    print(f"Data: {df.shape[0]} rows, {df.index[0].strftime('%Y-%m-%d')} to {df.index[-1].strftime('%Y-%m-%d')}")

    # === Indicators ===
    df['SMA_20'] = df['Close'].rolling(20).mean()
    df['SMA_50'] = df['Close'].rolling(50).mean()
    df['EMA_12'] = df['Close'].ewm(span=12).mean()
    df['EMA_26'] = df['Close'].ewm(span=26).mean()
    df['MACD'] = df['EMA_12'] - df['EMA_26']
    df['MACD_Signal'] = df['MACD'].ewm(span=9).mean()
    df['MACD_Hist'] = df['MACD'] - df['MACD_Signal']

    delta = df['Close'].diff()
    gain = delta.where(delta > 0, 0).rolling(14).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(14).mean()
    rs = gain / loss
    df['RSI'] = 100 - (100 / (1 + rs))

    df['BB_Mid'] = df['Close'].rolling(20).mean()
    df['BB_Std'] = df['Close'].rolling(20).std()
    df['BB_Upper'] = df['BB_Mid'] + 2 * df['BB_Std']
    df['BB_Lower'] = df['BB_Mid'] - 2 * df['BB_Std']

    df_plot = df.dropna().copy()

    # Print indicator summary
    print(f"\n=== INDICATOR SUMMARY ===")
    print(f"Close: {df['Close'].iloc[-1]:.2f}")
    print(f"SMA 20: {df['SMA_20'].iloc[-1]:.2f}")
    print(f"SMA 50: {df['SMA_50'].iloc[-1]:.2f}")
    print(f"RSI (14): {df['RSI'].iloc[-1]:.1f}")
    print(f"MACD: {df['MACD'].iloc[-1]:.2f}")
    print(f"MACD Signal: {df['MACD_Signal'].iloc[-1]:.2f}")
    print(f"BB Upper: {df['BB_Upper'].iloc[-1]:.2f}")
    print(f"BB Mid: {df['BB_Mid'].iloc[-1]:.2f}")
    print(f"BB Lower: {df['BB_Lower'].iloc[-1]:.2f}")

    recent = df.tail(60)
    pivot = (recent['High'].iloc[-1] + recent['Low'].iloc[-1] + recent['Close'].iloc[-1]) / 3
    print(f"\nPivot: {pivot:.2f}")
    print(f"R1: {2*pivot - recent['Low'].iloc[-1]:.2f}")
    print(f"S1: {2*pivot - recent['High'].iloc[-1]:.2f}")
    print(f"60d High: {recent['High'].max():.2f}")
    print(f"60d Low: {recent['Low'].min():.2f}")

    # === Style ===
    style = mpf.make_mpf_style(
        base_mpf_style='nightclouds',
        marketcolors=mpf.make_marketcolors(
            up='lime', down='red', edge='inherit', wick='inherit', volume='in'
        ),
        figcolor='#1a1a2f', gridcolor='#2a2a4a', facecolor='#1a1a2f'
    )

    apd = [
        mpf.make_addplot(df_plot['SMA_20'], color='orange', width=1.2),
        mpf.make_addplot(df_plot['SMA_50'], color='blue', width=1.2),
        mpf.make_addplot(df_plot['BB_Upper'], color='gray', linestyle='--', width=0.7),
        mpf.make_addplot(df_plot['BB_Lower'], color='gray', linestyle='--', width=0.7),
    ]

    # === Main Chart ===
    safe_ticker = ticker_str.replace('.', '_').replace(':', '_')
    chart_path = f'/tmp/{safe_ticker}_chart.png'
    rsi_path = f'/tmp/{safe_ticker}_rsi.png'
    macd_path = f'/tmp/{safe_ticker}_macd.png'

    fig, axes = mpf.plot(
        df_plot, type='candle', style=style,
        title=f'\n{ticker_str} — {period} Daily Chart',
        ylabel='Price', volume=True,
        addplot=apd, figsize=(16, 10),
        returnfig=True, tight_layout=True
    )
    fig.savefig(chart_path, dpi=150, bbox_inches='tight', facecolor=fig.get_facecolor())
    print(f"\nOK Chart: {chart_path}")

    # === RSI ===
    fig2, ax2 = plt.subplots(figsize=(16, 4), facecolor='#1a1a2f')
    ax2.plot(df_plot.index, df_plot['RSI'], color='cyan', linewidth=1.2)
    ax2.axhline(y=70, color='red', linestyle='--', alpha=0.7, label='Overbought (70)')
    ax2.axhline(y=30, color='lime', linestyle='--', alpha=0.7, label='Oversold (30)')
    ax2.axhline(y=50, color='gray', linestyle=':', alpha=0.5)
    ax2.fill_between(df_plot.index, df_plot['RSI'], 70, where=(df_plot['RSI'] >= 70), color='red', alpha=0.3)
    ax2.fill_between(df_plot.index, df_plot['RSI'], 30, where=(df_plot['RSI'] <= 30), color='lime', alpha=0.3)
    ax2.set_facecolor('#1a1a2f')
    ax2.tick_params(colors='white')
    for s in ax2.spines.values():
        s.set_color('white')
    ax2.set_ylabel('RSI', color='white')
    ax2.set_title('RSI (14)', color='white', fontsize=12)
    ax2.legend(loc='upper left', fontsize=9)
    fig2.savefig(rsi_path, dpi=150, bbox_inches='tight', facecolor=fig2.get_facecolor())
    print(f"OK RSI: {rsi_path}")

    # === MACD ===
    fig3, ax3 = plt.subplots(figsize=(16, 4), facecolor='#1a1a2f')
    ax3.plot(df_plot.index, df_plot['MACD'], color='cyan', linewidth=1.2, label='MACD')
    ax3.plot(df_plot.index, df_plot['MACD_Signal'], color='orange', linewidth=1.0, label='Signal')
    colors_bar = ['lime' if v >= 0 else 'red' for v in df_plot['MACD_Hist']]
    ax3.bar(df_plot.index, df_plot['MACD_Hist'], color=colors_bar, alpha=0.5, width=1.5)
    ax3.axhline(y=0, color='white', linewidth=0.5)
    ax3.set_facecolor('#1a1a2f')
    ax3.tick_params(colors='white')
    for s in ax3.spines.values():
        s.set_color('white')
    ax3.set_title('MACD (12, 26, 9)', color='white', fontsize=12)
    ax3.legend(loc='upper left', fontsize=9)
    fig3.savefig(macd_path, dpi=150, bbox_inches='tight', facecolor=fig3.get_facecolor())
    print(f"OK MACD: {macd_path}")

    print(f"\nALL DONE — Charts saved to /tmp/")
    return chart_path, rsi_path, macd_path

if __name__ == "__main__":
    ticker = sys.argv[1] if len(sys.argv) > 1 else "BBRI.JK"
    period = sys.argv[2] if len(sys.argv) > 2 else "6mo"
    generate(ticker, period)
